# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

 on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/15 * * * *'

          
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run Page Speed Insights     
      env:
        PAGE_SPEED_API_KEY: ${{ secrets.API_KEY }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        INFLUX_API_KEY: ${{ secrets.INFLUX_API_KEY }}
        INFLUX_URL: ${{ secrets.INFLUX_URL }}
        INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
      run: |
        python app.py -k ${PAGE_SPEED_API_KEY} -b ${BUCKET_NAME} -i ${INFLUX_API_KEY} -u ${INFLUX_URL} -o ${INFLUX_ORG}

    - name: Commit latest release version
      run: |
        git config --global user.name 'QAInsights'
        git config --global user.email 'catch.nkn@gmail.com'
        git commit -am "Updated the results"
        git push
